//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VirtualPrinter.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VirtualPrinter.Properties.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About_Title {
            get {
                return ResourceManager.GetString("About_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        public static string About_Version {
            get {
                return ResourceManager.GetString("About_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close the window..
        /// </summary>
        public static string Close_Tooltip {
            get {
                return ResourceManager.GetString("Close_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse for a folder to specify where label images are cached..
        /// </summary>
        public static string Configuration_Button_Browse_Tooltip {
            get {
                return ResourceManager.GetString("Configuration_Button_Browse_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to edit ZPL filters..
        /// </summary>
        public static string Configuration_Button_Filters_Tooltip {
            get {
                return ResourceManager.GetString("Configuration_Button_Filters_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Configuration_View_Button_Add_Text {
            get {
                return ResourceManager.GetString("Configuration_View_Button_Add_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a new printer configuration..
        /// </summary>
        public static string Configuration_View_Button_Add_Tooltip {
            get {
                return ResourceManager.GetString("Configuration_View_Button_Add_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clone.
        /// </summary>
        public static string Configuration_View_Button_Clone_Text {
            get {
                return ResourceManager.GetString("Configuration_View_Button_Clone_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clone the selected printer configuration..
        /// </summary>
        public static string Configuration_View_Button_Clone_Tooltip {
            get {
                return ResourceManager.GetString("Configuration_View_Button_Clone_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure.
        /// </summary>
        public static string Configuration_View_Button_Configure_Text {
            get {
                return ResourceManager.GetString("Configuration_View_Button_Configure_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to edit the physical printer..
        /// </summary>
        public static string Configuration_View_Button_Configure_Tooltip {
            get {
                return ResourceManager.GetString("Configuration_View_Button_Configure_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Configuration_View_Button_Delete_Text {
            get {
                return ResourceManager.GetString("Configuration_View_Button_Delete_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete the selected printer configuration..
        /// </summary>
        public static string Configuration_View_Button_Delete_Tooltip {
            get {
                return ResourceManager.GetString("Configuration_View_Button_Delete_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Configuration_View_Button_Save_Text {
            get {
                return ResourceManager.GetString("Configuration_View_Button_Save_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save changes to the current printer configuration..
        /// </summary>
        public static string Configuration_View_Button_Save_Tooltip {
            get {
                return ResourceManager.GetString("Configuration_View_Button_Save_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undo.
        /// </summary>
        public static string Configuration_View_Button_Undo_Text {
            get {
                return ResourceManager.GetString("Configuration_View_Button_Undo_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undo the current changes..
        /// </summary>
        public static string Configuration_View_Button_Undo_Tooltip {
            get {
                return ResourceManager.GetString("Configuration_View_Button_Undo_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host Address.
        /// </summary>
        public static string Configuration_View_Label_HostAddress {
            get {
                return ResourceManager.GetString("Configuration_View_Label_HostAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Label Cache.
        /// </summary>
        public static string Configuration_View_Label_LabelCache {
            get {
                return ResourceManager.GetString("Configuration_View_Label_LabelCache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Label Height.
        /// </summary>
        public static string Configuration_View_Label_LabelHeight {
            get {
                return ResourceManager.GetString("Configuration_View_Label_LabelHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Label Units.
        /// </summary>
        public static string Configuration_View_Label_LabelUnits {
            get {
                return ResourceManager.GetString("Configuration_View_Label_LabelUnits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Label Width.
        /// </summary>
        public static string Configuration_View_Label_LabelWidth {
            get {
                return ResourceManager.GetString("Configuration_View_Label_LabelWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Configuration_View_Label_Name {
            get {
                return ResourceManager.GetString("Configuration_View_Label_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Physical Printer.
        /// </summary>
        public static string Configuration_View_Label_PhysicalPrinter {
            get {
                return ResourceManager.GetString("Configuration_View_Label_PhysicalPrinter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TCP Port.
        /// </summary>
        public static string Configuration_View_Label_TcpPort {
            get {
                return ResourceManager.GetString("Configuration_View_Label_TcpPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Printer Configuration.
        /// </summary>
        public static string Configuration_View_Title {
            get {
                return ResourceManager.GetString("Configuration_View_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save changes to the current printer..
        /// </summary>
        public static string Configure_Printer_Button_Save_Tooltip {
            get {
                return ResourceManager.GetString("Configure_Printer_Button_Save_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure Printer.
        /// </summary>
        public static string Configure_Printer_Title {
            get {
                return ResourceManager.GetString("Configure_Printer_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TEST.
        /// </summary>
        public static string Connectivity_Test_Label_Text {
            get {
                return ResourceManager.GetString("Connectivity_Test_Label_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}Getting IP address for host name &apos;{1}.
        /// </summary>
        public static string Connectivity_Test_Message_Dns {
            get {
                return ResourceManager.GetString("Connectivity_Test_Message_Dns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}DNS lookup failed [FAILED].
        /// </summary>
        public static string Connectivity_Test_Message_Dns_Failed {
            get {
                return ResourceManager.GetString("Connectivity_Test_Message_Dns_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}Test completed with one or more failures.
        /// </summary>
        public static string Connectivity_Test_Message_Failed {
            get {
                return ResourceManager.GetString("Connectivity_Test_Message_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}Found {1} address for host name [OK].
        /// </summary>
        public static string Connectivity_Test_Message_Host {
            get {
                return ResourceManager.GetString("Connectivity_Test_Message_Host", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}IP address &apos;{1}&apos; was found for host name &apos;{2}&apos; [OK].
        /// </summary>
        public static string Connectivity_Test_Message_Ip {
            get {
                return ResourceManager.GetString("Connectivity_Test_Message_Ip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}Checking port &apos;{1}&apos; connectivity for IP address for host name &apos;{2}&apos;.
        /// </summary>
        public static string Connectivity_Test_Message_PortTest {
            get {
                return ResourceManager.GetString("Connectivity_Test_Message_PortTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}Connection to port &apos;{1}&apos; was unsuccessful [FAILED].
        /// </summary>
        public static string Connectivity_Test_Message_PortTest_Failed {
            get {
                return ResourceManager.GetString("Connectivity_Test_Message_PortTest_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}Connection to port &apos;{1}&apos; was successful [OK].
        /// </summary>
        public static string Connectivity_Test_Message_PortTest_Success {
            get {
                return ResourceManager.GetString("Connectivity_Test_Message_PortTest_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Testing connectivity to &apos;{0}&apos;.
        /// </summary>
        public static string Connectivity_Test_Message_Start {
            get {
                return ResourceManager.GetString("Connectivity_Test_Message_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}Test completed successfully.
        /// </summary>
        public static string Connectivity_Test_Message_Success {
            get {
                return ResourceManager.GetString("Connectivity_Test_Message_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}{1}/{2} API method connection was unsuccessful [FAILED].
        /// </summary>
        public static string Connectivity_Test_Message_WebMethod_Failed {
            get {
                return ResourceManager.GetString("Connectivity_Test_Message_WebMethod_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}Checking {1}/{2} API method connection.
        /// </summary>
        public static string Connectivity_Test_Message_WebMethodTest {
            get {
                return ResourceManager.GetString("Connectivity_Test_Message_WebMethodTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}{1}/{2} API method connection was successful [OK].
        /// </summary>
        public static string Connectivity_Test_Message_WebMethodTest_Success {
            get {
                return ResourceManager.GetString("Connectivity_Test_Message_WebMethodTest_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test Labelary Connection.
        /// </summary>
        public static string Connectivity_Test_Title {
            get {
                return ResourceManager.GetString("Connectivity_Test_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start the connection test..
        /// </summary>
        public static string Connectivity_TestButton_Start_Tooltip {
            get {
                return ResourceManager.GetString("Connectivity_TestButton_Start_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dpmm.
        /// </summary>
        public static string dpmm {
            get {
                return ResourceManager.GetString("dpmm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a new filter before this one..
        /// </summary>
        public static string Edit_Filters_Button_Add_Tooltip {
            get {
                return ResourceManager.GetString("Edit_Filters_Button_Add_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel the changes and close the dialog..
        /// </summary>
        public static string Edit_Filters_Button_Cancel_Tooltip {
            get {
                return ResourceManager.GetString("Edit_Filters_Button_Cancel_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete the this filter..
        /// </summary>
        public static string Edit_Filters_Button_Delete_Tooltip {
            get {
                return ResourceManager.GetString("Edit_Filters_Button_Delete_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move this filter down..
        /// </summary>
        public static string Edit_Filters_Button_Down_Tooltip {
            get {
                return ResourceManager.GetString("Edit_Filters_Button_Down_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save the changes and close the dialog..
        /// </summary>
        public static string Edit_Filters_Button_Ok_Tooltip {
            get {
                return ResourceManager.GetString("Edit_Filters_Button_Ok_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move this filter up..
        /// </summary>
        public static string Edit_Filters_Button_Up_Tooltip {
            get {
                return ResourceManager.GetString("Edit_Filters_Button_Up_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Treat Find as Regular Expression..
        /// </summary>
        public static string Edit_Filters_CheckBox_RegEx_Text {
            get {
                return ResourceManager.GetString("Edit_Filters_CheckBox_RegEx_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The filters are processed in the order they appear, from top to bottom..
        /// </summary>
        public static string Edit_Filters_Label {
            get {
                return ResourceManager.GetString("Edit_Filters_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find.
        /// </summary>
        public static string Edit_Filters_Label_Find {
            get {
                return ResourceManager.GetString("Edit_Filters_Label_Find", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace.
        /// </summary>
        public static string Edit_Filters_Label_Replace {
            get {
                return ResourceManager.GetString("Edit_Filters_Label_Replace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Filters.
        /// </summary>
        public static string Edit_Filters_Title {
            get {
                return ResourceManager.GetString("Edit_Filters_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel the changes and close the dialog..
        /// </summary>
        public static string Edit_Printer_Button_Cancel_Tooltip {
            get {
                return ResourceManager.GetString("Edit_Printer_Button_Cancel_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Send to Printer.
        /// </summary>
        public static string Edit_Printer_Checkbox_Text {
            get {
                return ResourceManager.GetString("Edit_Printer_Checkbox_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horizontal Alignment.
        /// </summary>
        public static string Edit_Printer_Group_Text_Horizontal {
            get {
                return ResourceManager.GetString("Edit_Printer_Group_Text_Horizontal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertical Alignment.
        /// </summary>
        public static string Edit_Printer_Group_Text_Vertical {
            get {
                return ResourceManager.GetString("Edit_Printer_Group_Text_Vertical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When enabled, the image retrieved for the label is sent to this printer..
        /// </summary>
        public static string Edit_Printer_Label {
            get {
                return ResourceManager.GetString("Edit_Printer_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bottom Margin.
        /// </summary>
        public static string Edit_Printer_Label_BottomMargin {
            get {
                return ResourceManager.GetString("Edit_Printer_Label_BottomMargin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left Margin.
        /// </summary>
        public static string Edit_Printer_Label_LeftMargin {
            get {
                return ResourceManager.GetString("Edit_Printer_Label_LeftMargin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right Margin.
        /// </summary>
        public static string Edit_Printer_Label_RightMargin {
            get {
                return ResourceManager.GetString("Edit_Printer_Label_RightMargin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Printer.
        /// </summary>
        public static string Edit_Printer_Label_SelectPrinter {
            get {
                return ResourceManager.GetString("Edit_Printer_Label_SelectPrinter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top Margin.
        /// </summary>
        public static string Edit_Printer_Label_TopMargin {
            get {
                return ResourceManager.GetString("Edit_Printer_Label_TopMargin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bottom.
        /// </summary>
        public static string Edit_Printer_RadioButton_Bottom {
            get {
                return ResourceManager.GetString("Edit_Printer_RadioButton_Bottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Center.
        /// </summary>
        public static string Edit_Printer_RadioButton_Center {
            get {
                return ResourceManager.GetString("Edit_Printer_RadioButton_Center", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left.
        /// </summary>
        public static string Edit_Printer_RadioButton_Left {
            get {
                return ResourceManager.GetString("Edit_Printer_RadioButton_Left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Middle.
        /// </summary>
        public static string Edit_Printer_RadioButton_Middle {
            get {
                return ResourceManager.GetString("Edit_Printer_RadioButton_Middle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right.
        /// </summary>
        public static string Edit_Printer_RadioButton_Right {
            get {
                return ResourceManager.GetString("Edit_Printer_RadioButton_Right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top.
        /// </summary>
        public static string Edit_Printer_RadioButton_Top {
            get {
                return ResourceManager.GetString("Edit_Printer_RadioButton_Top", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Filters.
        /// </summary>
        public static string Filters_None {
            get {
                return ResourceManager.GetString("Filters_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Font_Manager_Button_Add_Text {
            get {
                return ResourceManager.GetString("Font_Manager_Button_Add_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a new custom font..
        /// </summary>
        public static string Font_Manager_Button_Add_Tooltip {
            get {
                return ResourceManager.GetString("Font_Manager_Button_Add_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse for a local TrueType font source file..
        /// </summary>
        public static string Font_Manager_Button_Browse_Tooltip {
            get {
                return ResourceManager.GetString("Font_Manager_Button_Browse_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel the current changes and/or close the Font Manager..
        /// </summary>
        public static string Font_Manager_Button_Cancel_Tooltip {
            get {
                return ResourceManager.GetString("Font_Manager_Button_Cancel_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete this font from the Font Manager..
        /// </summary>
        public static string Font_Manager_Button_Delete_Tooltip {
            get {
                return ResourceManager.GetString("Font_Manager_Button_Delete_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string Font_Manager_Button_Ok_Text {
            get {
                return ResourceManager.GetString("Font_Manager_Button_Ok_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save the changes and close the Font Manager..
        /// </summary>
        public static string Font_Manager_Button_Ok_Tooltip {
            get {
                return ResourceManager.GetString("Font_Manager_Button_Ok_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save the current changes to this font..
        /// </summary>
        public static string Font_Manager_Button_Save_Tooltip {
            get {
                return ResourceManager.GetString("Font_Manager_Button_Save_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update the font using Labelary API..
        /// </summary>
        public static string Font_Manager_Button_Update_Tooltip {
            get {
                return ResourceManager.GetString("Font_Manager_Button_Update_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load custom TrueType fonts to be used in labels. Virtual ZPL Printer will automatically upload the fonts with the each label request to simulate fonts already loaded in the printer..
        /// </summary>
        public static string Font_Manager_Label {
            get {
                return ResourceManager.GetString("Font_Manager_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Byte Count.
        /// </summary>
        public static string Font_Manager_Label_ByteCount {
            get {
                return ResourceManager.GetString("Font_Manager_Label_ByteCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If provided, the font will be subset to contain only the specified characters..
        /// </summary>
        public static string Font_Manager_Label_CharacterDescription {
            get {
                return ResourceManager.GetString("Font_Manager_Label_CharacterDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Characters.
        /// </summary>
        public static string Font_Manager_Label_Characters {
            get {
                return ResourceManager.GetString("Font_Manager_Label_Characters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font Source.
        /// </summary>
        public static string Font_Manager_Label_FontSource {
            get {
                return ResourceManager.GetString("Font_Manager_Label_FontSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Printer Path.
        /// </summary>
        public static string Font_Manager_Label_PrinterPath {
            get {
                return ResourceManager.GetString("Font_Manager_Label_PrinterPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font Manager.
        /// </summary>
        public static string Font_Manager_Title {
            get {
                return ResourceManager.GetString("Font_Manager_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found.
        /// </summary>
        public static string Font_Source_Found {
            get {
                return ResourceManager.GetString("Font_Source_Found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing.
        /// </summary>
        public static string Font_Source_Missing {
            get {
                return ResourceManager.GetString("Font_Source_Missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete the selected font?.
        /// </summary>
        public static string Font_ViewModel_Dialog_Delete_Text {
            get {
                return ResourceManager.GetString("Font_ViewModel_Dialog_Delete_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Font.
        /// </summary>
        public static string Font_ViewModel_Dialog_Delete_Title {
            get {
                return ResourceManager.GetString("Font_ViewModel_Dialog_Delete_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TrueType Font|*.ttf|All Files|*.*.
        /// </summary>
        public static string Font_ViewModel_Dialog_Filter {
            get {
                return ResourceManager.GetString("Font_ViewModel_Dialog_Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select TrueType Font File.
        /// </summary>
        public static string Font_ViewModel_Dialog_Title {
            get {
                return ResourceManager.GetString("Font_ViewModel_Dialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The font does not support sub-setting characters..
        /// </summary>
        public static string FontConversion_Error {
            get {
                return ResourceManager.GetString("FontConversion_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel the changes and close the dialog..
        /// </summary>
        public static string Global_Settings_Button_Cancel_Toolip {
            get {
                return ResourceManager.GetString("Global_Settings_Button_Cancel_Toolip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save the changes and close the dialog..
        /// </summary>
        public static string Global_Settings_Button_Ok_Toolip {
            get {
                return ResourceManager.GetString("Global_Settings_Button_Ok_Toolip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Linting.
        /// </summary>
        public static string Global_Settings_Checkbox_EnableLinting_Text {
            get {
                return ResourceManager.GetString("Global_Settings_Checkbox_EnableLinting_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Labelary.
        /// </summary>
        public static string Global_Settings_Group_Header_Labelary {
            get {
                return ResourceManager.GetString("Global_Settings_Group_Header_Labelary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TCP Settings.
        /// </summary>
        public static string Global_Settings_Group_Header_TCP {
            get {
                return ResourceManager.GetString("Global_Settings_Group_Header_TCP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API URL.
        /// </summary>
        public static string Global_Settings_Label_ApiUrl {
            get {
                return ResourceManager.GetString("Global_Settings_Label_ApiUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linger.
        /// </summary>
        public static string Global_Settings_Label_Linger {
            get {
                return ResourceManager.GetString("Global_Settings_Label_Linger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linger Time (seconds).
        /// </summary>
        public static string Global_Settings_Label_LingerTime {
            get {
                return ResourceManager.GetString("Global_Settings_Label_LingerTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method.
        /// </summary>
        public static string Global_Settings_Label_Method {
            get {
                return ResourceManager.GetString("Global_Settings_Label_Method", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Delay.
        /// </summary>
        public static string Global_Settings_Label_NoDelay {
            get {
                return ResourceManager.GetString("Global_Settings_Label_NoDelay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receive Buffer Size (bytes).
        /// </summary>
        public static string Global_Settings_Label_ReceiveBufferSize {
            get {
                return ResourceManager.GetString("Global_Settings_Label_ReceiveBufferSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received Data Encoding.
        /// </summary>
        public static string Global_Settings_Label_ReceivedDataEncoding {
            get {
                return ResourceManager.GetString("Global_Settings_Label_ReceivedDataEncoding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receive Timeout (ms).
        /// </summary>
        public static string Global_Settings_Label_ReceiveTimeout {
            get {
                return ResourceManager.GetString("Global_Settings_Label_ReceiveTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Buffer Size (bytes).
        /// </summary>
        public static string Global_Settings_Label_SendBufferSize {
            get {
                return ResourceManager.GetString("Global_Settings_Label_SendBufferSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Timeout (ms).
        /// </summary>
        public static string Global_Settings_Label_SendTimeout {
            get {
                return ResourceManager.GetString("Global_Settings_Label_SendTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to These settings are applied to the incoming request from an external application..
        /// </summary>
        public static string Global_Settings_Label_Tcp {
            get {
                return ResourceManager.GetString("Global_Settings_Label_Tcp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global Settings.
        /// </summary>
        public static string Global_Settings_Title {
            get {
                return ResourceManager.GetString("Global_Settings_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GET.
        /// </summary>
        public static string Global_Settings_WebMethod_Get {
            get {
                return ResourceManager.GetString("Global_Settings_WebMethod_Get", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to POST.
        /// </summary>
        public static string Global_Settings_WebMethod_Post {
            get {
                return ResourceManager.GetString("Global_Settings_WebMethod_Post", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Any.
        /// </summary>
        public static string HostAddress_Any {
            get {
                return ResourceManager.GetString("HostAddress_Any", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loopback.
        /// </summary>
        public static string HostAddress_Loopback {
            get {
                return ResourceManager.GetString("HostAddress_Loopback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        public static string HostAddress_Unknown {
            get {
                return ResourceManager.GetString("HostAddress_Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Main_Button_Delete_Text {
            get {
                return ResourceManager.GetString("Main_Button_Delete_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete the selected label..
        /// </summary>
        public static string Main_Button_Delete_Tooltip {
            get {
                return ResourceManager.GetString("Main_Button_Delete_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Main_Button_Edit_Text {
            get {
                return ResourceManager.GetString("Main_Button_Edit_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit printer configurations..
        /// </summary>
        public static string Main_Button_Edit_Toolip {
            get {
                return ResourceManager.GetString("Main_Button_Edit_Toolip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string Main_Button_Start_Text {
            get {
                return ResourceManager.GetString("Main_Button_Start_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start the virtual printer..
        /// </summary>
        public static string Main_Button_Start_Tooltip {
            get {
                return ResourceManager.GetString("Main_Button_Start_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        public static string Main_Button_Stop_Text {
            get {
                return ResourceManager.GetString("Main_Button_Stop_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop the virtual printer from accepting label request..
        /// </summary>
        public static string Main_Button_Stop_Tooltip {
            get {
                return ResourceManager.GetString("Main_Button_Stop_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test.
        /// </summary>
        public static string Main_Button_Test_Text {
            get {
                return ResourceManager.GetString("Main_Button_Test_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send a test label..
        /// </summary>
        public static string Main_Button_Test_Tooltip {
            get {
                return ResourceManager.GetString("Main_Button_Test_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string Main_Button_View_Text {
            get {
                return ResourceManager.GetString("Main_Button_View_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View the label image in an external viewer..
        /// </summary>
        public static string Main_Button_View_Tooltip {
            get {
                return ResourceManager.GetString("Main_Button_View_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string Main_ButtonClear_Text {
            get {
                return ResourceManager.GetString("Main_ButtonClear_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear all labels..
        /// </summary>
        public static string Main_ButtonClear_Tooltip {
            get {
                return ResourceManager.GetString("Main_ButtonClear_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto-Start.
        /// </summary>
        public static string Main_Checkbox_AutoStart {
            get {
                return ResourceManager.GetString("Main_Checkbox_AutoStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Connection.
        /// </summary>
        public static string Main_Menu_Connection {
            get {
                return ResourceManager.GetString("Main_Menu_Connection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test Labelary.
        /// </summary>
        public static string Main_Menu_Connection_Test_Labelary {
            get {
                return ResourceManager.GetString("Main_Menu_Connection_Test_Labelary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Options.
        /// </summary>
        public static string Main_Menu_Options {
            get {
                return ResourceManager.GetString("Main_Menu_Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string Main_Menu_Options_About {
            get {
                return ResourceManager.GetString("Main_Menu_Options_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global Settings.
        /// </summary>
        public static string Main_Menu_Options_Global_Settings {
            get {
                return ResourceManager.GetString("Main_Menu_Options_Global_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Printer.
        /// </summary>
        public static string Main_Menu_Printer {
            get {
                return ResourceManager.GetString("Main_Menu_Printer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string Main_Menu_Printer_Clear {
            get {
                return ResourceManager.GetString("Main_Menu_Printer_Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Main_Menu_Printer_Delete {
            get {
                return ResourceManager.GetString("Main_Menu_Printer_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Main_Menu_Printer_Edit {
            get {
                return ResourceManager.GetString("Main_Menu_Printer_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font Manager.
        /// </summary>
        public static string Main_Menu_Printer_FontManager {
            get {
                return ResourceManager.GetString("Main_Menu_Printer_FontManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string Main_Menu_Printer_Start {
            get {
                return ResourceManager.GetString("Main_Menu_Printer_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        public static string Main_Menu_Printer_Stop {
            get {
                return ResourceManager.GetString("Main_Menu_Printer_Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test.
        /// </summary>
        public static string Main_Menu_Printer_Test {
            get {
                return ResourceManager.GetString("Main_Menu_Printer_Test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string Main_Menu_Printer_View {
            get {
                return ResourceManager.GetString("Main_Menu_Printer_View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Idle.
        /// </summary>
        public static string Main_Status_Idle {
            get {
                return ResourceManager.GetString("Main_Status_Idle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to label.
        /// </summary>
        public static string Main_Status_Label {
            get {
                return ResourceManager.GetString("Main_Status_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to labels.
        /// </summary>
        public static string Main_Status_Labels {
            get {
                return ResourceManager.GetString("Main_Status_Labels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listening.
        /// </summary>
        public static string Main_Status_Listening {
            get {
                return ResourceManager.GetString("Main_Status_Listening", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading cached labels....
        /// </summary>
        public static string Main_Status_LoadingLabels {
            get {
                return ResourceManager.GetString("Main_Status_LoadingLabels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to of.
        /// </summary>
        public static string Main_Status_Of {
            get {
                return ResourceManager.GetString("Main_Status_Of", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready.
        /// </summary>
        public static string Main_Status_Ready {
            get {
                return ResourceManager.GetString("Main_Status_Ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Viewing label.
        /// </summary>
        public static string Main_Status_ViewingLabel {
            get {
                return ResourceManager.GetString("Main_Status_ViewingLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no cached labels.
        /// </summary>
        public static string Main_TextBlock_NoCachedLabels {
            get {
                return ResourceManager.GetString("Main_TextBlock_NoCachedLabels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active Printer Configuration.
        /// </summary>
        public static string Main_TextBlock_SelectConfiguration {
            get {
                return ResourceManager.GetString("Main_TextBlock_SelectConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Virtual ZPL Printer.
        /// </summary>
        public static string Main_Title {
            get {
                return ResourceManager.GetString("Main_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete printer configuration &apos;{0}&apos;?.
        /// </summary>
        public static string MessageBox_DeletePrinterConfiguration_Message {
            get {
                return ResourceManager.GetString("MessageBox_DeletePrinterConfiguration_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Printer Configuration.
        /// </summary>
        public static string MessageBox_DeletePrinterConfiguration_Title {
            get {
                return ResourceManager.GetString("MessageBox_DeletePrinterConfiguration_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete failed..
        /// </summary>
        public static string MessageBox_DeletePrinterConfigurationFailed_Message {
            get {
                return ResourceManager.GetString("MessageBox_DeletePrinterConfigurationFailed_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Printer Configuration.
        /// </summary>
        public static string MessageBox_DeletePrinterConfigurationFailed_Title {
            get {
                return ResourceManager.GetString("MessageBox_DeletePrinterConfigurationFailed_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown Exception.
        /// </summary>
        public static string MessageBox_Exception_Title {
            get {
                return ResourceManager.GetString("MessageBox_Exception_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Converting Font.
        /// </summary>
        public static string MessageBox_FontConversion_Exception_Title {
            get {
                return ResourceManager.GetString("MessageBox_FontConversion_Exception_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Printer Configuration.
        /// </summary>
        public static string New_Printer_Configuration_Name {
            get {
                return ResourceManager.GetString("New_Printer_Configuration_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disabled.
        /// </summary>
        public static string Printer_Configuration_Disabled {
            get {
                return ResourceManager.GetString("Printer_Configuration_Disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabled.
        /// </summary>
        public static string Printer_Configuration_Enabled {
            get {
                return ResourceManager.GetString("Printer_Configuration_Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host.
        /// </summary>
        public static string Printer_Configuration_Host {
            get {
                return ResourceManager.GetString("Printer_Configuration_Host", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        public static string Printer_Configuration_Id {
            get {
                return ResourceManager.GetString("Printer_Configuration_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Printing.
        /// </summary>
        public static string Printer_Configuration_Printing {
            get {
                return ResourceManager.GetString("Printer_Configuration_Printing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resolution.
        /// </summary>
        public static string Printer_Configuration_Resolution {
            get {
                return ResourceManager.GetString("Printer_Configuration_Resolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotation.
        /// </summary>
        public static string Printer_Configuration_Rotation {
            get {
                return ResourceManager.GetString("Printer_Configuration_Rotation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size.
        /// </summary>
        public static string Printer_Configuration_Size {
            get {
                return ResourceManager.GetString("Printer_Configuration_Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to by.
        /// </summary>
        public static string PrinterConfigurationViewModel_By {
            get {
                return ResourceManager.GetString("PrinterConfigurationViewModel_By", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        public static string Send_Test_Label_Button_Text {
            get {
                return ResourceManager.GetString("Send_Test_Label_Button_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send the selected test label to the virtual printer..
        /// </summary>
        public static string Send_Test_Label_Button_Tooltip {
            get {
                return ResourceManager.GetString("Send_Test_Label_Button_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Test Label.
        /// </summary>
        public static string Send_Test_Label_Select {
            get {
                return ResourceManager.GetString("Send_Test_Label_Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Test Label.
        /// </summary>
        public static string Send_Test_Label_Title {
            get {
                return ResourceManager.GetString("Send_Test_Label_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ZPL Viewer.
        /// </summary>
        public static string ZPL_Viewer_Title {
            get {
                return ResourceManager.GetString("ZPL_Viewer_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ZPL Warnings.
        /// </summary>
        public static string ZPL_Warnings {
            get {
                return ResourceManager.GetString("ZPL_Warnings", resourceCulture);
            }
        }
    }
}
