//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VirtualPrinter.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VirtualPrinter.Properties.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About_Title {
            get {
                return ResourceManager.GetString("About_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        public static string About_Version {
            get {
                return ResourceManager.GetString("About_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Main_Button_Delete_Text {
            get {
                return ResourceManager.GetString("Main_Button_Delete_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete the selected label..
        /// </summary>
        public static string Main_Button_Delete_Tooltip {
            get {
                return ResourceManager.GetString("Main_Button_Delete_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Main_Button_Edit_Text {
            get {
                return ResourceManager.GetString("Main_Button_Edit_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit printer configurations..
        /// </summary>
        public static string Main_Button_Edit_Toolip {
            get {
                return ResourceManager.GetString("Main_Button_Edit_Toolip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string Main_Button_Start_Text {
            get {
                return ResourceManager.GetString("Main_Button_Start_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start the virtual printer..
        /// </summary>
        public static string Main_Button_Start_Tooltip {
            get {
                return ResourceManager.GetString("Main_Button_Start_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        public static string Main_Button_Stop_Text {
            get {
                return ResourceManager.GetString("Main_Button_Stop_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop the virtual printer from accepting label request..
        /// </summary>
        public static string Main_Button_Stop_Tooltip {
            get {
                return ResourceManager.GetString("Main_Button_Stop_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test.
        /// </summary>
        public static string Main_Button_Test_Text {
            get {
                return ResourceManager.GetString("Main_Button_Test_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send a test label..
        /// </summary>
        public static string Main_Button_Test_Tooltip {
            get {
                return ResourceManager.GetString("Main_Button_Test_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string Main_Button_View_Text {
            get {
                return ResourceManager.GetString("Main_Button_View_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View the label image in an external viewer..
        /// </summary>
        public static string Main_Button_View_Tooltip {
            get {
                return ResourceManager.GetString("Main_Button_View_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string Main_ButtonClear_Text {
            get {
                return ResourceManager.GetString("Main_ButtonClear_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear all labels..
        /// </summary>
        public static string Main_ButtonClear_Tooltip {
            get {
                return ResourceManager.GetString("Main_ButtonClear_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto-Start.
        /// </summary>
        public static string Main_Checkbox_AutoStart {
            get {
                return ResourceManager.GetString("Main_Checkbox_AutoStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Connection.
        /// </summary>
        public static string Main_Menu_Connection {
            get {
                return ResourceManager.GetString("Main_Menu_Connection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Options.
        /// </summary>
        public static string Main_Menu_Options {
            get {
                return ResourceManager.GetString("Main_Menu_Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Printer.
        /// </summary>
        public static string Main_Menu_Printer {
            get {
                return ResourceManager.GetString("Main_Menu_Printer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Idle.
        /// </summary>
        public static string Main_Status_Idle {
            get {
                return ResourceManager.GetString("Main_Status_Idle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listening.
        /// </summary>
        public static string Main_Status_Listening {
            get {
                return ResourceManager.GetString("Main_Status_Listening", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no cached labels.
        /// </summary>
        public static string Main_TextBlock_NoCachedLabels {
            get {
                return ResourceManager.GetString("Main_TextBlock_NoCachedLabels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active Printer Configuration.
        /// </summary>
        public static string Main_TextBlock_SelectConfiguration {
            get {
                return ResourceManager.GetString("Main_TextBlock_SelectConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Virtual ZPL Printer.
        /// </summary>
        public static string Main_Title {
            get {
                return ResourceManager.GetString("Main_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
    }
}
